- internal/cli/command/organization/list.go
- internal/cli/command/organization/select.go
- internal/cli/command/secret/cmd.go
- internal/cli/command/secret/get.go
- internal/cli/command/secret/list.go
- internal/cli/format/secret.go
- internal/cli/output/output.go
* Implement secret get
* Fix output flag
* Implement listing with type filter.
closed #20
> Improve secret read operations

- cmd/cluster.go
> clusterCreate: fix response fields

- .circleci/config.yml
- .gitignore
- .goreleaser.yml
- Makefile
- cmd/banzai/main.go
- cmd/root.go
> Finalize binary release process

- .golangci.yml
- cmd/root.go
- internal/cli/command/cluster/cmd.go
- internal/cli/command/cluster/create.go
- internal/cli/command/cluster/legacy.go
- internal/cli/command/cluster/legacy_organization.go
- internal/cli/command/cluster/legacy_root.go
- internal/cli/command/cluster/utils.go
> Cluster create file option

- .circleci/config.yml
Fix GO111MODULE value in .circle.yml
> Fix GO111MODULE value in .circle.yml

- internal/cli/command/secret/cmd.go
- internal/cli/command/secret/delete.go
> Implement secret deletion

- internal/cli/command/cluster/legacy.go
> Add environment variables to cluster shell

- internal/cli/command/controlplane/up.go
> cp: remove values editing

- internal/cli/command/form/web/package-lock.json
- internal/cli/command/form/web/package.json
> form: update uniform

- cmd/root.go
- internal/cli/command/cluster/cmd.go
- internal/cli/command/cluster/create.go
- internal/cli/command/cluster/delete.go
- internal/cli/command/cluster/legacy.go
* add missing docs and verbose output
* review aliases
* add delete --force option
* wait for cluster creation
* fix cluster defaults
* propagate `cluster sh` exit code
> Enhance cluster commands

- internal/cli/command/cluster/install_secret.go
Fix install secret help description
> Fix install secret help description

- Makefile
- cmd/docs/banzai.md
- cmd/docs/banzai_cluster.md
- cmd/docs/banzai_cluster_create.md
- cmd/docs/banzai_cluster_delete.md
- cmd/docs/banzai_cluster_get.md
- cmd/docs/banzai_cluster_install.md
- cmd/docs/banzai_cluster_install_secret.md
- cmd/docs/banzai_cluster_list.md
- cmd/docs/banzai_cluster_shell.md
- cmd/docs/banzai_controlplane.md
- cmd/docs/banzai_controlplane_down.md
- cmd/docs/banzai_controlplane_up.md
- cmd/docs/banzai_form.md
- cmd/docs/banzai_form_migrate.md
- cmd/docs/banzai_form_open.md
- cmd/docs/banzai_form_template.md
- cmd/docs/banzai_login.md
- cmd/docs/banzai_organization.md
- cmd/docs/banzai_organization_list.md
- cmd/docs/banzai_organization_select.md
- cmd/docs/banzai_secret.md
- cmd/docs/banzai_secret_delete.md
- cmd/docs/banzai_secret_get.md
- cmd/docs/banzai_secret_list.md
- cmd/docs/generate.go
- cmd/root.go
- go.mod
- go.sum
> Gen cli docs

- internal/cli/cli.go
- internal/cli/command/cluster/cmd.go
- internal/cli/command/cluster/helm.go
- internal/cli/command/cluster/shell.go
> Helm integration for `banzai cluster shell`

- .goreleaser.yml
according to: https://goreleaser.com/homebrew/
> brew: depends_on "kubectl"

- internal/cli/input/check.go
- internal/cli/input/organization.go
> Check pipeline endpoint

- go.mod
- go.sum
- internal/cli/cli.go
- internal/cli/command/cmd.go
- internal/cli/command/login/login.go
- internal/cli/command/login/oidc.go
execute OIDC based login flow (if no token is provided during the banzai login command)
> Login flow

- cmd/docs/banzai_cluster_delete.md
- cmd/docs/banzai_cluster_get.md
- cmd/docs/banzai_cluster_shell.md
- cmd/docs/banzai_login.md
- go.mod
- go.sum
- internal/cli/cli.go
- internal/cli/command/login/login.go
Normally, a session token would be used
> Generate permanent token after login

- internal/cli/cli.go
- internal/cli/command/login/oidc.go
> cli: add pipeline.tls-skip-verify and tls-ca-cert config

- .circleci/config.yml
- .goreleaser.yml
- Makefile
Provide better support for Linux.
> Generate rpm + deb packages for releases

- internal/cli/command/controlplane/up.go
> print login command after up

- .circleci/config.yml
- .goreleaser.yml
- README.md
> release: push artifacts to s3

- README.md
- scripts/getcli.sh
- scripts/test_getcli.sh
`curl https://getpipeline.sh/cli | sh [-s -- auto|deb|rpm|brew|tar|go|kubectl]`
> add getcli.sh for oneliner installer

- internal/cli/input/check.go
Fix possible nil pointer dereference
> Fix possible nil pointer dereference

- internal/cli/command/cluster/create.go
Fix PKE AWS default cluster parameters
> Fix PKE AWS default cluster parameters (#101)

- cmd/docs/banzai.md
- cmd/docs/banzai_cluster_feature.md
- cmd/docs/banzai_cluster_feature_dns.md
- cmd/docs/banzai_cluster_feature_dns_activate.md
- cmd/docs/banzai_cluster_feature_dns_deactivate.md
- cmd/docs/banzai_cluster_feature_dns_get.md
- cmd/docs/banzai_cluster_feature_dns_update.md
- cmd/docs/banzai_cluster_feature_list.md
- cmd/docs/banzai_pipeline.md
- cmd/docs/banzai_pipeline_down.md
- cmd/docs/banzai_pipeline_init.md
- cmd/docs/banzai_pipeline_up.md
- cmd/docs/banzai_secret_create.md
- go.mod
- internal/cli/command/cluster/cmd.go
- internal/cli/command/cluster/context/context.go
- internal/cli/command/cluster/delete.go
- internal/cli/command/cluster/feature/cmd.go
- internal/cli/command/cluster/feature/features/dns/activate.go
- internal/cli/command/cluster/feature/features/dns/cmd.go
- internal/cli/command/cluster/feature/features/dns/common.go
- internal/cli/command/cluster/feature/features/dns/deactivate.go
- internal/cli/command/cluster/feature/features/dns/get.go
- internal/cli/command/cluster/feature/features/dns/update.go
- internal/cli/command/cluster/feature/list.go
- internal/cli/command/cluster/get.go
- internal/cli/command/cluster/shell.go
- internal/cli/command/secret/install.go
- internal/cli/format/clusterfeature.go
Basic support for listing cluster features and activating, deactivating, updating and querying the DNS feature (non-interactive and editor-only flows).
> Cluster features MVP

- internal/cli/command/cluster/create.go
Fix more panics.
AlecAivazis/survey#243
> cluster: fix survey panics

- .golangci.yml
- internal/cli/command/cluster/import.go
- internal/cli/command/controlplane/ec2.go
- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/installer_options.go
- internal/cli/command/controlplane/kind.go
- internal/cli/command/controlplane/up.go
- internal/cli/command/login/login.go
- internal/cli/command/secret/create.go
- internal/cli/input/secret.go
port kubeconfig rewrite and localhost/dfm logic to the cli
| Bug fix?        | no|yes
> Fixes for existing k8s installer

- internal/cli/command/controlplane/ec2.go
- internal/cli/command/controlplane/up.go
> Fix ec2 down

- internal/cli/command/login/login.go
> login: don't request a new token if it is permanent already

- README.md
- cmd/docs/banzai_pipeline_down.md
- cmd/docs/banzai_pipeline_init.md
- cmd/docs/banzai_pipeline_up.md
- internal/cli/command/controlplane/down.go
- internal/cli/command/controlplane/ec2.go
- internal/cli/command/controlplane/exec.go
- internal/cli/command/controlplane/installer_options.go
- internal/cli/command/controlplane/up.go
Fix some edge cases and add development option:
* move cp exec functions to own file
* rename them to better represent their goals
* allow bypassing docker container  (`--run-locally`)
* fix non-tty exection
* fix behavior with different ssh client configs/envs
> Control plane exec improvements

- internal/cli/command/organization/list.go
- internal/cli/format/organization.go
```bash
$ banzai orgs list                                                                                   
Id  Name               Selected
2   admin-example-com  ✔       
2   some-other-org 
```
This way it looks better :)
> display selected org better

- internal/cli/command/cluster/feature/features/dns/activate.go
Fix result binding in case of DNS feature:
```
failed to build activate request interactively: failure during survey: Unable to convert from string to type slice
```
> Fix editor result binding in case of DNS feature

- internal/cli/command/controlplane/init.go
| Related tickets | N/A
Fix of a typo.
> cp init: fix command name in post run

- internal/cli/command/cluster/feature/features/get.go
> feature-get: sort fields before printing

- internal/cli/command/cluster/feature/features/vault/get.go
follow up on https://github.com/banzaicloud/pipeline/pull/2356/files
> vault-feature: simplify role output

- internal/cli/command/cluster/feature/cmd.go
- internal/cli/command/cluster/feature/features/dns/update.go
- internal/cli/command/cluster/feature/features/monitoring/activate.go
- internal/cli/command/cluster/feature/features/monitoring/common.go
- internal/cli/command/cluster/feature/features/monitoring/get.go
- internal/cli/command/cluster/feature/features/monitoring/input.go
- internal/cli/command/cluster/feature/features/monitoring/spec.go
- internal/cli/command/cluster/feature/features/monitoring/update.go
- internal/cli/command/cluster/feature/features/subcommand_dns.go
- internal/cli/command/cluster/feature/features/subcommand_monitoring.go
- internal/cli/command/cluster/feature/features/subcommand_vault.go
- internal/cli/command/cluster/feature/features/vault/update.go
> Introduce monitoring feature

- internal/cli/command/cluster/feature/features/dns/get.go
- internal/cli/command/cluster/feature/features/get.go
- internal/cli/command/cluster/feature/features/monitoring/activate.go
- internal/cli/command/cluster/feature/features/monitoring/common.go
- internal/cli/command/cluster/feature/features/monitoring/error.go
- internal/cli/command/cluster/feature/features/monitoring/get.go
- internal/cli/command/cluster/feature/features/monitoring/spec.go
- internal/cli/command/cluster/feature/features/monitoring/update.go
- internal/cli/command/cluster/feature/features/securityscan/get.go
- internal/cli/command/cluster/feature/features/vault/get.go
Support new monitoring feature payload
> Monitoring improvements

- internal/cli/command/controlplane/custom.go
- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/installer_options.go
1. remove local_file target in case of creating custom cluster
2. remove custom target in case of deleting custom cluster
>  minor fix for custom provider

- internal/cli/command/login/login.go
It caused errors when the user's clock is behind the server's.
> login: don't check issue time of jwt tokens

- internal/cli/command/controlplane/down.go
- internal/cli/command/controlplane/exec.go
Merge after https://github.com/banzaicloud/banzai-cli/pull/166
Tested with custom(eks) provider
> Fix custom provider

- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/installer_options.go
> Refactor installerImage handling

- internal/cli/command/cluster/create.go
Deploy latest PKE version by default
> Update default PKE version

- internal/cli/command/cluster/feature/cmd.go
- internal/cli/command/cluster/feature/features/logging/activate.go
- internal/cli/command/cluster/feature/features/logging/common.go
- internal/cli/command/cluster/feature/features/logging/error.go
- internal/cli/command/cluster/feature/features/logging/get.go
- internal/cli/command/cluster/feature/features/logging/spec.go
- internal/cli/command/cluster/feature/features/logging/update.go
- internal/cli/command/cluster/feature/features/monitoring/activate.go
- internal/cli/command/cluster/feature/features/subcommand_logging.go
- internal/cli/input/questions.go
> Support Logging feature

- cmd/docs/banzai_cluster_service.md
- cmd/docs/banzai_cluster_service_logging.md
- cmd/docs/banzai_cluster_service_logging_activate.md
- cmd/docs/banzai_cluster_service_logging_deactivate.md
- cmd/docs/banzai_cluster_service_logging_get.md
- cmd/docs/banzai_cluster_service_logging_update.md
- cmd/docs/banzai_pipeline_up.md
> Regenerate docs

- cmd/docs/banzai_cluster.md
- cmd/docs/banzai_cluster_nodepool.md
- cmd/docs/banzai_cluster_nodepool_create.md
- cmd/docs/banzai_cluster_nodepool_delete.md
- internal/cli/command/cluster/nodepool/cmd.go
- internal/cli/command/cluster/nodepool/create.go
- internal/cli/command/cluster/nodepool/delete.go
> Remove hidden flag from node pool commands

- internal/cli/command/controlplane/init.go
* store image details in values file for all providers (it was for custom only)
* better lowercase username instead of hostname
> Cp init fixes

- internal/cli/command/login/login.go
/token endpoint suggested by the help of the no-browser login flow no longer exists. Recommend the UI instead.
> login: fix help

- internal/cli/command/cluster/integratedservice/cmd.go
- internal/cli/command/cluster/integratedservice/services/activate.go
- internal/cli/command/cluster/integratedservice/services/common.go
- internal/cli/command/cluster/integratedservice/services/deactivate.go
- internal/cli/command/cluster/integratedservice/services/get.go
- internal/cli/command/cluster/integratedservice/services/update.go
Add capabilities check before all service commands
> [Service] Add capabilities check before all service commands

- internal/cli/command/cluster/integratedservice/cmd.go
- internal/cli/command/cluster/integratedservice/services/expiry/activate.go
- internal/cli/command/cluster/integratedservice/services/expiry/common.go
- internal/cli/command/cluster/integratedservice/services/expiry/get.go
- internal/cli/command/cluster/integratedservice/services/expiry/spec.go
- internal/cli/command/cluster/integratedservice/services/expiry/update.go
- internal/cli/command/cluster/integratedservice/services/subcommand_expiry.go
Support for new `Expiry` feature
```
$ banzai cluster service expiry activate
? Provide expiration date in UTC ( your local time in UTC is 2020-01-20T15:02:48Z ): 2020-01-20T15:03:48Z
? Are you sure you want this cluster to be deleted at 2020-01-20T15:03:48Z? Yes
? Do you want to edit the cluster service activation request in your text editor? No
INFO[0013] service "expiry" started to activate
```
> Support Expiry integrated service

- internal/cli/command/cluster/integratedservice/cmd.go
- internal/cli/command/cluster/integratedservice/services/activate.go
- internal/cli/command/cluster/integratedservice/services/expiry/spec.go
- internal/cli/command/cluster/integratedservice/services/expiry/update.go
- internal/cli/command/cluster/integratedservice/services/get.go
- internal/cli/command/cluster/integratedservice/services/update.go
Bugfixes related to integrated services:
- cluster related flags taken into account while operating integrated services
- fixed activation request assembly
- cluster flags were ignored by the tool when managing integrated services
- the request read from files (or stdin) were lost while activating integrated services
> fixes related to integrated services

- internal/cli/command/cluster/node/node_ssh.go
> ssh: fix use-internal/external-ip flag help texts

- internal/cli/command/cluster/integratedservice/services/logging/activate.go
- Fix default Secret and Bucket selection in case of interactive mode
- Hide hidden secrets
> [Logging] Fix default Secret and Bucket selection in case of interactive mode

- internal/cli/command/form/web/src/app/app.component.ts
> fix(form): remove unused code

- go.mod
- internal/cli/command/cluster/integratedservice/cmd.go
- internal/cli/command/cluster/integratedservice/services/activate.go
- internal/cli/command/cluster/integratedservice/services/common.go
- internal/cli/command/cluster/integratedservice/services/dns/manager.go
- internal/cli/command/cluster/integratedservice/services/expiry/manager.go
- internal/cli/command/cluster/integratedservice/services/ingress/common.go
- internal/cli/command/cluster/integratedservice/services/ingress/manager.go
- internal/cli/command/cluster/integratedservice/services/ingress/spec.go
- internal/cli/command/cluster/integratedservice/services/ingress/spec_test.go
- internal/cli/command/cluster/integratedservice/services/ingress/utils.go
- internal/cli/command/cluster/integratedservice/services/logging/manager.go
- internal/cli/command/cluster/integratedservice/services/monitoring/manager.go
- internal/cli/command/cluster/integratedservice/services/securityscan/manager.go
- internal/cli/command/cluster/integratedservice/services/update.go
- internal/cli/command/cluster/integratedservice/services/vault/manager.go
- pkg/stringslice/stringslice.go
Commands for the ingress integrated service.
To support manipulation of ingress integrated service from CLI.
> Ingress integrated service MVP

- internal/cli/command/cmd.go
- internal/cli/command/completion/cmd.go
| Related tickets | 
Add "completion" command for enhanced shell ux
> add completion command

- .circleci/config.yml
- scripts/trigger-docs-update.sh
> circleci: Trigger docs update on release tags

- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/up.go
| API breaks?     | yes
* Run terraform init for `banzai cp up` only
* Don't store the aws access key
* Remove support for custom installer images without metadata
To fix remote states.
> fix cp init with remote state

- internal/cli/command/cluster/base.go
- internal/cli/command/cluster/create.go
Support cluster create on Vsphere
> Support cluster create on Vsphere

- internal/cli/command/controlplane/exec.go
- internal/cli/command/controlplane/installer_options.go
Reverts banzaicloud/banzai-cli#224
> Revert "up: mount original tfstate for migrate"

- internal/cli/command/controlplane/exec.go
- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/installer_options.go
- internal/cli/command/controlplane/up.go
This PR fixes previous installer image versions broken by #224
> fix remote state migration backward compatibility

- internal/cli/format/cluster.go
Adding the location to output columns.
Valuable information.
> add location to cluster outputs

- internal/cli/command/login/oidc.go
Related to #229 to fix login backward compatibility.
> support the old user_sess cookie as well

- internal/cli/command/secret/create.go
Sort secret types alphabetically in the creation survey.
To have a constant order.
> Sort secret types alphabetically in the creation survey

- .circleci/config.yml
- .goreleaser.unstable.yml
- Makefile
Do not push dev releases to s3 and homebrew.
> circleci: introduce unstable release job

- internal/cli/command/controlplane/down.go
- internal/cli/command/controlplane/up.go
- internal/cli/command/controlplane/utils.go
Getting image metadata in case of pipeline down as well.
[x] custom provider
[x] ec2 single node
[x] kind
> Getting image metadata in case of cp down

- pkg/process/process.go
Fixes displaying multiple events of the same type.
> tail: fix event loop

- pkg/process/process.go
| Deprecations?   | temporary fix for #239 
- process: add process id to log
- process: don't let multiple statuses run simultaneously for now
> process: don't let multiple statuses run simultaneously for now

- internal/cli/command/login/oidc.go
| Related tickets | fixes #245 
Fix for using the same HTTP transport configured for the CLI in `getIdPURL`.
> use cli http transport in getIdPURL

- .goreleaser.yml
Install shell completions with Brew.
> Install shell completions

- README.md
> remove /cli from get script

- internal/cli/command/cluster/integratedservice/services/vault/manager.go
Provide a default policy for the current organization when enabling the Vault IS on a cluster, fix question formats.
It is hard to find out a good policy initally.
> vault is: add a default policy, fix question

- go.mod
- internal/cli/command/cluster/helm.go
- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/installer_options.go
- internal/cli/command/controlplane/utils.go
- internal/cli/input/secret.go
- internal/cli/output/output.go
| Related tickets |  #260 
Go back to `yaml.v2` at some places.
Fixes Yaml override issue introduced by #260
> import yaml.v2 as it used to be

- internal/cli/command/controlplane/kind.go
- internal/cli/command/controlplane/up.go
fixes banzaicloud/pipeline#2846
> allow specifying Kind bind address

- internal/cli/command/cluster/nodepool/update.go
Alias `nodepool update` to `nodepool upgrade`.
We use the terms `upgrade` and `update` interchangeably in the node-pool context.
> nodepool upgrade alias

- internal/cli/command/cluster/integratedservice/services/securityscan/common.go
- internal/cli/command/cluster/integratedservice/services/securityscan/manager.go
- internal/cli/command/cluster/integratedservice/utils/util.go
Allow passing a custom anchore policy interactively.
testdata:
```json
{"active":true,"blacklisted_images":[],"comment":"Reject images contais critical vulnerabilities","id":"reject_critical-2","last_updated":1593674310,"mappings":[{"id":"23d5b099-f6a2-42f8-9d75-4a0b41b405d7","image":{"type":"tag","value":"*"},"name":"reject_critical-2","policy_id":"3087043b-7e93-4ef4-b9ca-3b1df85bc46a","registry":"*","repository":"*","whitelist_ids":[]}],"name":"Reject critical bundle 2","policies":[{"comment":"Reject critical policy","id":"3087043b-7e93-4ef4-b9ca-3b1df85bc46a","name":"R …
```
> anchore: allow passing custom policy interactively

- internal/cli/command/cluster/integratedservice/services/securityscan/common.go
- internal/cli/command/cluster/integratedservice/services/securityscan/manager.go
Complete the Security Scan interactive registry questions and add the registry survey as well.
The code was there for the missing parts just wasn't wired together.
> anchore: fix survey and add interactive registry part

- internal/cli/command/controlplane/utils.go
- internal/cli/command/secret/create.go
- internal/cli/input/secret.go
| New feature?    |yes
- Add session token capability
- In the case of secret creation, the session token is turned off due to regression.
> AWS session token

- internal/cli/command/controlplane/init.go
- internal/cli/command/controlplane/utils.go
- internal/cli/command/secret/create.go
- internal/cli/input/secret.go
Support for setting for STS Assume role when using AWS credentials.
> aws: support for sts assume role

- internal/cli/command/cluster/node/node_ssh.go
If the node couldn't join the cluster, you can provide its IP address
and still use the ssh key automatically.
> ssh: allow ssh to arbitrary host

- internal/cli/command/cluster/integratedservice/services/backup/common.go
- internal/cli/command/cluster/integratedservice/services/backup/create.go
- internal/cli/command/cluster/integratedservice/services/backup/delete.go
- internal/cli/command/cluster/integratedservice/services/backup/disable.go
- internal/cli/command/cluster/integratedservice/services/backup/enable.go
- internal/cli/command/cluster/integratedservice/services/backup/list.go
- internal/cli/command/cluster/integratedservice/services/backup/status.go
- internal/cli/command/cluster/integratedservice/services/restore/common.go
- internal/cli/command/cluster/integratedservice/services/restore/create.go
- internal/cli/command/cluster/integratedservice/services/restore/delete.go
- internal/cli/command/cluster/integratedservice/services/restore/list.go
- internal/cli/command/cluster/integratedservice/services/restore/result.go
> CLI help texts for backup service

- internal/cli/command/controlplane/down.go
| Related tickets | fixes #157
Make no the default answer for pipeline destroy question
> Make no the default answer for pipeline destroy question

- internal/cli/input/secret.go
Enables the use of explicit environment variables to override the profile set in the providerConfig which should only be a convenience feature but shouldn't block explicit credentials.
> Make the installer work even if AWS profile has been set but overridden with env vars explicitly

- internal/cli/format/cluster.go
| Related tickets | N/A
Display the Kubernetes version in the `cluster list` subcommand.
Important information.
> cluster-list: display version

- cmd/root.go
> login: default to try.pipeline.banzai.cloud instead of beta

- cmd/root.go
- go.mod
- go.sum
- internal/cli/cli.go
- internal/cli/command/controlplane/cmd.go
- internal/cli/command/controlplane/debug.go
- internal/cli/command/controlplane/exec.go
- internal/cli/command/controlplane/installer_options.go
| Related tickets | closes #290 
Add `banzai pipeline debug` command that generates a debug bundle.
> Debug bundle

- internal/cli/command/controlplane/debug.go
Describe the contents of the debug bundle.
> debug: add details to help

- internal/cli/command/controlplane/debug.go
recommend encrypting the debug bundle
> debug: add gpg notice

- .github/workflows/docker.yaml
Fix docker image build (https://github.com/docker/build-push-action/issues/126)
> Fix build-push-action

- internal/cli/command/cluster/create.go
- internal/cli/command/cluster/templates.go
| Related tickets | fixes #293 
Add template option to cluster create command
> Add template option to cluster create command

- internal/cli/command/secret/create.go
> Minor error message fix

- internal/cli/cli.go
> allow verbose (curl) mode for all API clients

- internal/cli/command/cluster/integratedservice/services/backup/create.go
| Related tickets | #280 
Check the backup service status before creating a backup.
Otherwise, a somewhat cryptic error message bubbles up (with status 404).
> backup: check status before creation

- internal/cli/command/cluster/context/context.go
this made for example `banzai org select` saving the cluster id to
config when executed in a banzai shell
> cluster: don't bind current cluster id env var

- .gen/pipeline/api/openapi.yaml
- .gen/pipeline/docs/EksNodePool.md
- .gen/pipeline/docs/EksNodePoolAllOf.md
- .gen/pipeline/docs/EksUpdateNodePoolRequest.md
- .gen/pipeline/docs/EksUpdateNodePoolRequestAllOf.md
- .gen/pipeline/docs/NodePool.md
- .gen/pipeline/docs/NodePoolSummary.md
- .gen/pipeline/docs/UpdateNodePoolRequest.md
- .gen/pipeline/model_eks_node_pool.go
- .gen/pipeline/model_eks_node_pool_all_of.go
- .gen/pipeline/model_eks_update_node_pool_request.go
- .gen/pipeline/model_eks_update_node_pool_request_all_of.go
- .gen/pipeline/model_node_pool.go
- .gen/pipeline/model_node_pool_summary.go
- .gen/pipeline/model_update_node_pool_request.go
- .gen/pipeline/version.go
- Makefile
Regenrate pipeline API, to include useInstanceStore param.
> regenerate pipeline API

- .github/workflows/docker.yaml
Fix for missing `--version` info in the docker images.
> pass tagged version to docker build

- internal/cli/command/controlplane/utils.go
this is useful for testing s3 based helm repos locally
| Related tickets | banzaicloud/pipeline-installer#159
> cp: add hidden passAWSCredentials option for kind

- .goreleaser.yml
Changed `blob` -> `blobs`
`blob` was deprecated in the config of newer versions of goreleaser.
> Fixed goreleaser config

- .goreleaser.yml
Added region to blob in goreleaser.
Uploading the artifacts to S3 bucket failed without a region parameter for some reason.
- ~Related Helm chart(s) updated (if needed~
> Added AWS regon to goreleaser blob

- .github/workflows/release-stable.yaml
Used make target to release with goreleaser
So LDFLAGS env has correct value
> Used make target to release with goreleaser

- .github/workflows/release-stable.yaml
- .goreleaser.yml
Fixed releasing to homebrew by using org-wide github token
> Fixed homebrew release
