internal/cli/command/cluster/create.go

Fixing bug. `banzai cluster create -f clusters/dev/multi-node.json --no-interactive` tried to read from stdin, `-f` handling was not implemented on the non-interactive branch

cluster: fix -f + --no-interactive cluster creation

---

cmd/root.go
internal/cli/command/cluster/legacy.go

use env vars from #49  for selecting org/cluster in banzai-cli itself, and start cluster shell even if config is not yet available

Fix env var usage

---

cmd/banzai/main.go
internal/cli/cli.go
internal/cli/command/controlplane/down.go
internal/cli/command/controlplane/up.go
internal/cli/command/controlplane/utils.go
internal/cli/command/login.go

* copy kubeconfig to working dir temporarily (because /tmp is out of DfM default
shared paths)
* don't offer editing of values file during `cp down`
* fix input values editing during `cp up`

cp: rewrite input file handling

---

internal/cli/command/controlplane/up.go

On Edge it is called: `Docker Desktop`
On Stable it is: `Docker for Mac`

Fix docker for mac detection

---

internal/cli/command/cluster/install.go
internal/cli/command/cluster/install_secret.go

```
Usage:
banzai cluster install secret [flags]
Aliases:
secret, s
Flags:
-c, --cluster-name string   Name of the cluster to install the secret
-f, --file string           Template descriptor file
-h, --help                  help for secret
-m, --merge                 Set true to merge existing secret
-s, --secret-name string    Name of the secret to install
```
Example:
```
banzai cluster install secret -s mySecretName -c myClusterName <<EOF
{
"namespace": "default",
"sourceSecretName": "mysql76rvg-mysql-root-password",
"spec": {
"ROOT_USER": {
"source": "username"
},
"ROOT_PASSWORD": {
"source": "password"
}
}
}
EOF
```
fixes #62

Add install secret to cluster commands

---

cmd/docs/banzai_secret.md
cmd/docs/banzai_secret_create.md
internal/cli/command/cluster/create.go
internal/cli/command/cluster/install_secret.go
internal/cli/command/controlplane/up.go
internal/cli/command/controlplane/utils.go
internal/cli/command/secret/cmd.go
internal/cli/command/secret/create.go
internal/cli/utils/utils.go

| Related tickets | fixes #19 
```
Usage:
banzai secret create [flags]
Aliases:
create, c
Examples:
Create secret
---
$ banzai secret create
? Secret name mysecretname
? Choose secret type: password
? Set 'username' field: myusername
? Set 'password' field: mypassword
? Do you want to add tag(s) to this secret? Yes
? Tag: tag1
? Tag: tag2
? Tag: skip
Create secret with flags
---
$ banzai secret create --name mysecretname --type password --tags=cli
? Set 'username' field: myusername
? Set 'password' field: mypassword
Flags:
-f, --file string        Secret creation descriptor file
-h, --help               help for create
-n, --name string        Name of the secret
--tags stringArray   Tags to add to …
```

Add secret create command

---

cmd/docs/banzai_controlplane_down.md
cmd/docs/banzai_controlplane_up.md
go.mod
internal/cli/command/controlplane/down.go
internal/cli/command/controlplane/installer_options.go
internal/cli/command/controlplane/up.go

| Related tickets | fixes #74  
banzai cp up
----
```
Create controlplane based on json stdin or interactive session in the current Kubernetes context. The current working directory will be used for storing the applied configuration and deployment status.
Usage:
banzai controlplane up [flags]
Aliases:
up, c
Flags:
-f, --file string                Input control plane descriptor file (default "values.yaml")
-h, --help                       help for up
--installer-tag string       Tag of cp-installer (default "latest")
--installer-tag-force-pull   Pull tag of cp-installer (default true)
Global Flags:
--color                use colors on non-tty outputs
--config string …
```

controlplane up/down: add image-tag and image-pull flags

---

internal/cli/command/cluster/create.go

Sort the offered cloud provider list instead of presenting them in the natural order of the map keys.

cluster: sort providers on interactive create survey

---

internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/installer_options.go
internal/cli/command/controlplane/up.go

Add a hidden `--refresh-state` option which can be turned off for quicker deployment during development, and fix external host record hint for all providers.

cp: add --refresh-state=true option

---

go.mod
internal/cli/command/login/oidc.go

| Related tickets | https://github.com/banzaicloud/pipeline/pull/2274 https://github.com/banzaicloud/pipeline/pull/2268
This PR requests the offline OIDC scope and sends the corresponding refresh token to Pipeline as well.
Because this is needed after:
- https://github.com/banzaicloud/pipeline/pull/2274
- https://github.com/banzaicloud/pipeline/pull/2268

login: request offline scope and send refresh token

---

internal/cli/command/controlplane/installer_options.go

and alert the user if a folder named like the workspace exists in the
current pwd
Handle the `.` and `..` special files as a `--workspace` option properly, because it would mean `~/.banzai/pipeline/.` = `~/.banzai/pipeline` and `~/.banzai/pipeline/..` = `~/.banzai` respectively. Now they are handled as relative to the current working directory (just like other paths that contain a slash).
Also, warn the user if `./workspace-name-given` exists.

cp: handle "." and ".." specially

---

internal/cli/cli.go
internal/cli/command/login/oidc.go
internal/cli/utils/http2curl.go

If started with `--verbose` the CLI will print the executed HTTP requests as cURL commands.
This is really helpful during development and debugging flows.

output HTTP requests as curl commands in verbose mode

---

internal/cli/command/cluster/feature/features/monitoring/activate.go
internal/cli/command/cluster/feature/features/monitoring/spec.go

Make providers of Alertmanager optional

[Monitoring] Make providers of Alertmanager optional

---

internal/cli/command/cluster/feature/features/activate.go
internal/cli/command/cluster/feature/features/dns/activate.go
internal/cli/command/cluster/feature/features/dns/common.go
internal/cli/command/cluster/feature/features/dns/update.go
internal/cli/command/cluster/feature/features/monitoring/activate.go
internal/cli/command/cluster/feature/features/monitoring/update.go
internal/cli/command/cluster/feature/features/securityscan/activate.go
internal/cli/command/cluster/feature/features/securityscan/update.go
internal/cli/command/cluster/feature/features/update.go
internal/cli/command/cluster/feature/features/vault/activate.go
internal/cli/command/cluster/feature/features/vault/update.go

- cluster context (holding the cluster name) inferred to the request assembler methods
Banzai Cloud DNS:
- cluster domain made readonly
- default domain filter set to the cluster domain
Route53
- add region, batchSize options
- Fixed the org domain in case of Banzai Cloud DNS
- Fixed the update flow to  Banzai Cloud DNS

Improve the support for the DNS cluster feature

---

internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/init.go
internal/cli/command/controlplane/up.go

Remote state support preparation for `pipeline up`. Currently, only the same file-based backend (`local`) is used, but in a backend fashion, so extending this with custom remote backends should be straightforward.

pipeline: preparing support for remote state

---

internal/cli/command/controlplane/exec.go

Terraform was running on one thread until now because of limitations in the installer image. This PR removes that limitation from the CLI.
Since those issues were resolved in the upstream installer image (helm repo update, namespace destroy, etc..) we can remove the single thread limitation thus making the installation process faster.
Tested on:
- KIND
- Docker for Mac - Kubernetes
- EC2 PKE

terraform can run now in full parallel mode

---

internal/cli/command/controlplane/init.go

```banzai cp init --no-interactive --image=pipeline-installer --image-pull=false --image-tag=local --provider kind
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/banzaicloud/banzai-cli/internal/cli/command/controlplane.runInit(0x0, 0x0, 0x7ffdc3e942e2, 0x4, 0xc0001d1f10, 0x19f7660, 0xc0001e41e0, 0x0, 0xc000141c90)
/home/circleci/project/internal/cli/command/controlplane/init.go:170 +0x21aa
```

cp: fix panic on empty non-interactive stdin

---

internal/cli/command/controlplane/down.go

To be able to test stack deletion locally and in CI easily.

cp: destroy stack on kind cluster as well

---

internal/cli/command/controlplane/up.go

Makes nothing if the resource is not present. Required when computed values used in resource `count`.
In case we use a computed value from a resource to set the count for another resource the following error happens:
```
Error: Invalid count argument
on asd.tf line 8, in data "template_file" "asd":
8:   count    = var.enabled ? 1 : 0
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
As the error message suggest we …

Preapply hook 

---

internal/cli/command/controlplane/init.go

eks (and possibly other providers) don't allow dots in cluster names
while a typical Mac has a long hostname

cp: suggest valid cluster name

---

go.mod
internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/init.go
internal/cli/command/controlplane/installer_options.go
internal/cli/command/controlplane/up.go

Adding support for storing installer state in Terraform `remote state` backends: https://www.terraform.io/docs/backends/types/remote.html
1. `banzai cp init`
2. Add the following snippet to the `~/.banzai/pipeline/default/values.yaml` file:
```yaml
state:
terraform:
backend:
s3:
bucket: my-tf-bucket
key: "path/to/my/key"
region: "eu-west-1"
access_key: ******
secret_key: ******
```
3. `banzai cp up`

cp: enable remote state configuration

---

internal/cli/command/controlplane/exec.go

Don't ask any questions on init and force copy remote state to new backend.

installer: force-copy remote state on init

---

internal/cli/command/controlplane/exec.go

Make sure that init parameters are only included in the init command.

Fix init command parameters

---

.gitignore
internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/utils.go

`banzai pipeline` commands provide a `backend-config` file for `terraform init` command, if a `state.tfvars` file is found in the workspace.
This change lets us provide state backend credentials in an uncommited file.

Terraform init backend config

---

internal/cli/command/controlplane/init.go

Make the providerConfig be persisted explicitly in all cases if it's not empty

---

internal/cli/command/cluster/helm.go

needed for helm plugin install commands
`helm plugin install URL` didn't work in a banzai cluster shell:
`Error: plugin home "$HELM_HOME/plugins" does not exist`

helm: create plugins dir

---

internal/cli/command/cluster/node/node_ssh.go

* ask username interactively
* remove default username for pke (it can be different, and the error reporting is not the best if the default is wrong)
* add -p shorthand for `--pod-connect --use-internal-ip`

banzai cluster node ssh UX improvements

---

internal/cli/command/cluster/create.go

| Related tickets | 
Allow changing the cluster name from the command line:
```
banzai cluster create --name my-cluster -f descriptor.json
```
When using predefined templates updating the name manually in the cluster descriptor is painful.

Allow changing the cluster name from the command line

---

internal/cli/command/cluster/integratedservice/services/common.go

Converting the keys of the map which contains enabled services to lowercase in case of checking feature enablement.

Using lowercase service names in case of checking services.

---

internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/installer_options.go

Mounting the original tfstate file to the working directory before state migration.
Otherwise, the migration will get completed without any state.
Installer image required: 0.4.11

up: mount original tfstate for migrate

---

internal/cli/cli.go
internal/cli/command/login/oidc.go

| Related tickets | https://github.com/banzaicloud/pipeline/pull/2860
A `Client` (similarly to the `Server` header) header is added, so servers can detect the CLI.

add client header to requests

---

internal/cli/command/cluster/cmd.go
internal/cli/command/cluster/config.go

Support to download K8S config to the current folder.
```
Get K8S config
Usage:
banzai cluster config [--cluster=ID | [--cluster-name=]NAME] [flags]
Aliases:
config, co
Flags:
--cluster int32         ID of cluster to config
--cluster-name string   Name of cluster to config
-h, --help                  help for config
-p, --path string           Path to save cluster K8S config
Global Flags:
--color                use colors on non-tty outputs
--config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
--interactive          ask questions interactively even if stdin or stdout is non-tty …
```

Add cluster config command

---

internal/cli/command/cluster/nodepool/create.go
internal/cli/command/cluster/nodepool/update.go
internal/cli/command/cluster/nodepool/update/cancel.go
internal/cli/command/cluster/nodepool/update/tail.go
internal/cli/command/cluster/nodepool/update/util.go

| Bug fix?        | no|yes
| Related tickets | #235
Move out hidden process subcommands to `cluster nodepool update` specific forms.
Usage examples:
```
$ banzai cluster nodepool update tail 06017cef-d1c2-4a2e-a07a-fd0f4b40755b
$ banzai cluster nodepool update cancel 06017cef-d1c2-4a2e-a07a-fd0f4b40755b
```

add nodepool update cancel and tail subcommand

---

internal/cli/command/cluster/nodepool/update.go

Fixing (back) --flag availability in `nodepool update`.

fix nodepool update flag locality

---

go.sum
internal/cli/command/cluster/nodepool/update/cancel.go
internal/cli/command/cluster/nodepool/update/tail.go
internal/cli/command/process/cancel.go
internal/cli/command/process/list.go
internal/cli/command/process/tail.go
pkg/process/process.go

- Standard error handling for process-related commands without printing usage after failure.
- Tail commands don't error if process failed/canceled.

fix process error handling

---

internal/cli/command/cluster/context/context.go

Error handling was broken for empty organizations.
This caused the CLI to send a malformed request to Pipeline where `clusterID` was 0, instead of returning a "404"-ish error to the user.

fix cluster context in org without clusters

---

internal/cli/command/cluster/helm.go
internal/cli/command/cluster/shell.go

| New feature?    |yes
This PR contains implementations of the helm 3 support.
- `helm` command calls the helm version 3 (helm version gets from Pipeline API)
- `helm2` command calls the helm version 2 (helm version gets from tiller)
- in case of helm 3 is supported by Pipeline and tiller is still on the cluster, a warning message will appear.

Helm3 support

---

internal/cli/command/controlplane/ec2.go

| Related tickets | 
This PR fixes EC2 SSH auth when the SSH agent already has a large number of keys in it.
When using a generated keypair, make sure to only use it, otherwise the user might run into `Too many authentication failures` errors.

Make sure to use the generated SSH key

---

go.mod
go.sum
pkg/process/process.go

| Related tickets | fixes #239 
Previously the process tail displayed events in a different order when it tailed "live" vs. when it tailed a completed process, none of them was correct, but live ordering was more close to correct. This PR resolves this issue and straightens event ordering for both cases.
We still can't display concurrent process activities in a fully instant fashion (having multiple spinners at the same time) but that is for another PR. We display them correctly at least now.

consistent event order in process tail

---

internal/cli/command/cluster/helm.go

Fix helm version detection with older pipeline versions, or newer versions where helm3 is disabled.
Currently the version is detected as `v%!s(<nil>)` due to trying to fill a non existent field as a version string.

Fix version detection when helm3 is not yet enabled

---

pkg/process/process.go

Don't hit the API hard when polling the process log.

process-log: don't hit the API hard when polling

---

internal/cli/command/controlplane/exec.go
internal/cli/command/controlplane/installer_options.go
internal/cli/command/controlplane/utils.go

Avoid setting the KUBECONFIG env var for terraform commands as the installer image already contains the path where it expects it's kubeconfig. 
The latest installer image will require the updated banzai-cli to find its kubeconfig at the right location.
Existing deployments above installer version 0.4.1 (inclusive) should still be upgradeable and destroyable with the latest image as well since their image has the KUBECONFIG=/workspace/kubeconfig environment variable baked in.

Kubeconfig path management updates

---

internal/cli/command/cluster/integratedservice/services/securityscan/common.go

Allow specifying a custom registry in the security scan enablement command.

scan: add registry configurability support

---

internal/cli/command/controlplane/up.go

Fix the setup of the useGeneratedKey variable.
The error occurred due to the false value of the useGeneratedKey.
```retrieve kubernetes config from cluster "ec2-54-185-225-73.us-west-2.compute.amazonaws.com"
INFO[0029] ssh -oStrictHostKeyChecking=no -l centos ec2-54-185-225-73.us-west-2.compute.amazonaws.com sudo cat /etc/kubernetes/admin.conf
centos@ec2-54-185-225-73.us-west-2.compute.amazonaws.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
failed to create EC2 cluster: failed to retrieve …
```

fix using generated ssh key in case of ec2 provider

---

internal/cli/input/secret.go

Increasing the STS session duration to 1 hour, which is the AWS account default globally.
To have longer sessions compared to the default 15 minutes.

sts: increase session duration to 1 hour

---

.gitignore

This PR added cmd/docs/*.md files to the repository level .gitignore file to be ignored.
It is convenient to hide these files from the git file changes as feature development usually requires adjusting the documentation as well, which can be easily verified with the generated local documentation.
These documentation files are also changing dynamically which would require extra efforts to be kept in sync on the repository remote thus committing them would not be feasible.
This practice might be opinionated, so feel free to engage in a discussion about whether the content of this PR would be a useful …

chore(git): ignore generated local documentation files at cmd/docs/*.md

---

internal/cli/command/cluster/shell.go

Exit with error message when `banzai cluster shell` is run within another session.
It's almost always confusing and never useful to nest such sessions.

shell: quit when nesting banzai cluster shell

---

internal/cli/command/controlplane/utils.go
internal/cli/input/secret.go

| Fixes | #265  |
Enables the use of the AWS_PROFILE env variable in case of a custom AWS provider where otherwise a profile is set in the config file. Warn in case if it has to be overridden.
Without an env var the config cannot be overridden to a custom profile, if the user has it under a different name for example.

Make the installer work with AWS_PROFILE set as an environment variable (warn if overrides config file setting).

---

internal/cli/utils/http2curl.go

| Related tickets | N/A
The header slice was preallocated in `GetCurlCommand` and prefilled with empty values, but it should be only preallocated.
```
DEBU[0000] curl -k -X 'GET' -H ': ' -H ': ' -H ': ' -H 'Accept: application/json'
vs.
DEBU[0000] curl -k -X 'GET' -H 'Accept: application/json'
```

fix slice allocation in GetCurlCommand

---

internal/cli/command/cluster/nodepool/delete.go

| New feature?    | yes (command output)
| Related tickets | resolves #288 
Added a success describing informational message to `banzai cluster nodepool delete` based on the response status.
Success codes can come from two statuses a, `202 Accepted` deletion initiated and b, `204 No Content` node pool not found and if the user doesn't notice a typo in the node pool name a silent success may shadow issues and generate cost by not deleting the node pool. With such an informational message it is immediately determinable whether the deletion was successfully initiated.
```yaml
nodePool:
- does not exist
- exists
```
<details>
<summary>Node pool does …

feat(cl/np/delete): added response-based info msg

---

.github/workflows/docker.yaml
Dockerfile
README.md

Build a docker image with all the runtime deps of banzai cli that can be used in a ci flow or a kubernetes task.

build docker image

---

.goreleaser.unstable.yml
.goreleaser.yml
Makefile

| Related tickets | resolves #306 
Fixed the `banzai --version` output (missing Pipeline version).
The ` main.pipelineVersion` value definition was missing from the Goreleaser configuration which caused the Pipeline version to not be set in the released binary.
<details>
<summary>Solution reasoning</summary>
Tried fixing it in the Goreleaser configuration, but dynamic information is very difficult to be configured there.
Failed with 
1. env (added literally),
2. build hook (implemented by the documentation, failing the schema check),
3. global hook (not changing environment through command),
so I was pretty much up to …

fix(goreleaser): fixed ldflags & Pipeline version

---

internal/cli/command/cluster/nodepool/list.go
internal/cli/format/node_pools.go

Added subnet ID to `banzai cluster nodepool list` output.
It is an argument specified at node pool creation which should be returned on node pool list, previously it was missing from the API output.
Documentation [PR](https://github.com/banzaicloud/banzaicloud.github.io/pull/1839).
Pipeline [PR](https://github.com/banzaicloud/pipeline/pull/3180).
Tested with old API, works fine with empty value.

fix(cl/np/list): added subnet ID

---

.licensei.toml
internal/cli/auth/login.go

| Deprecations?   | yes
| Related tickets | N/A
Removing the presence check fo the user_sess cookie, which is not sent by Pipeline a long ago.

login: remove old user_sess cookie support

---

internal/cli/command/cluster/context/context.go

| Related tickets | #280 
Set cluster cloud even if cluster.id is defined in options. This was missing.
Otherwise, the `"Deploy cluster secret to give access for Velero to make volume snapshots"` feature in the backup service won't work.

backup: set cluster.cloud in options in every case

---

internal/cli/command/cluster/restore/create.go
internal/cli/command/cluster/restore/result.go

| Related tickets | #271 
Add restore-id handling to the `banzai cluster restore result` subcommand.
It was suggested it exists, but it didn't.

backup: implement restore-id handling

---

internal/cli/command/cluster/integratedservice/services/securityscan/common.go
internal/cli/command/cluster/integratedservice/services/securityscan/manager.go

| New feature?    |yes
| Related tickets | related https://github.com/banzaicloud/pipeline/pull/3403
Implement supporting multiple image registries in `securityscan` integrated service.

feat(securityscan): add multiple registries

---

.circleci/config.yml

Fixed CircleCI RPM install on stable release
Previously it failed (example: https://app.circleci.com/pipelines/github/banzaicloud/banzai-cli/1497/workflows/92b60448-2cd2-44dc-ab08-7e685d05dab7/jobs/2647) because some packages were not found.
After SSHing into the worker node a simple package registry update seems to resolve it.
Tested.

Fixed CircleCI RPM install on stable release

---

Makefile

Fixed GoReleaser install in the build.
Broke on CI when releasing a new stable version.
https://app.circleci.com/pipelines/github/banzaicloud/banzai-cli/1501/workflows/f1c04f5d-a262-480d-bbed-423e6a177c0e/jobs/2652
Fixed by replacing the deprecated GoReleaser install script.
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~

Fixed GoReleaser install in the build

---

internal/cli/command/cluster/delete.go

This change affects the log after a successful cluster delete:
- set the log level of the http response to debug
- set the log level of the action info message to info
- decapitalize the action info message to match the style of similar logs
- change misleading variable name holding the http response object
It is unnecessary to log the response from the api when deleting a cluster, but can be useful when debugging.
```
? Do you want to DELETE the cluster? Yes
INFO[0009] Deleting cluster &{202 Accepted 202 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Wed, 03 Nov 2021 14:43:06 GMT]] 0xc0003fa600 0 [] …
```

fix: split cluster delete log to different levels

---

internal/cli/command/cluster/create.go

| Related PRs | https://github.com/banzaicloud/pipeline/pull/3587
Return a `cluster XYZ is already being created` message if the response code of cluster create is 201 Created.
If the cluster creation is called with the wait flag (`-w`) on the same cluster name repeatedly, it floods the terminal with an error message because in this case a cluster object is not returned that could be watched, so the function needs to return before that would happen.
- ~[] User guide and development docs updated (if needed)~
- ~[] Related Helm chart(s) updated (if needed)~

Handle double create 201 response

---

Makefile
internal/cli/command/cluster/shell.go
pkg/kubectlversion/kubectlversion.go

Update apiVersion `client.authentication.k8s.io/v1alpha1` -> `client.authentication.k8s.io/v1beta1` on machines having kubectl 1.24 and greater installed in the kubeconfig returned by the command `banzai cluster shell`.
In kubectl version 1.24 `client.authentication.k8s.io/v1alpha1` has been deprecated, so on machines that have the latest kubectl version installed this apiVersion needs to be updated.
Temporary fix until Pipeline itself returns the kubeconfig with the updated apiVersion.

Fix authentication apiversion in kubeconfig

---

internal/cli/command/controlplane/init.go
internal/cli/command/controlplane/kind.go

Run `fixKind0_9_0KubeProxy` method on linux systems as well.
Similar to the issue solved by [this previous PR](https://github.com/banzaicloud/banzai-cli/pull/353), the same fix is also needed on linux.
Tested on `ubuntu-latest` Github Actions runner.

Run `fixKind0_9_0KubeProxy` method on linux systems

---

.github/workflows/release-stable.yaml

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no|
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | - |
| License         | Apache 2.0 |
Replaced `::set-output` with `>> $GITHUB_OUTPUT`
Deprecated, will be removed in 2023-05-31.
Details: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
Tested [in another PR](https://github.com/banzaicloud/koperator/pull/906/files#diff-dce4cd1ca1dc3e5849de0fd3f3c7b132ad537e4ba79ba191f5de4330484b214bR39), worked well.
- ~Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)~
- ~Logging code meets the guideline~
- ~User guide and …

Replaced GHA `set-output` with `GITHUB_OUTPUT`
